version: "3"

volumes:
  mongodbdata:
    driver: local

services:
  node:
    container_name: "${PROJECT_NAME}_node"
    image: node:$NODE_TAG
    working_dir: /usr/src/app
    restart: unless-stopped
    user: 'node'
    links:
      - mongodb
    volumes:
      - .:/usr/src/app
    command: tail -f /dev/null
    ports:
      - "9229:9229"

  mongodb:
    container_name: "${PROJECT_NAME}_mongodb"
    image: mongo:$MONGODB_TAG
    # Use to set initial password
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=
    #   - MONGO_INITDB_ROOT_PASSWORD=
    restart: unless-stopped
    volumes:
      - mongodbdata:/data/db
    command: 'mongod --auth'
    ports:
      - "127.0.0.1:27017:27017"
