name: Deploy

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Updating the remote docker container to the latest version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: docker-compose -f "docker-compose.yml" down && docker-compose pull jrambaud/gerardbot:latest && docker-compose -f "docker-compose.yml" --env-file ".env" up -d --build
